// ─── British National Curriculum — Full Seed Data ─────────────────────────────

export const defaultSubjects = [
  { name:"Mathematics",      nameAr:"الرياضيات",          slug:"mathematics",   description:"Numbers, algebra, geometry, statistics",     iconEmoji:"🔢", color:"#3b82f6", stages:["kindergarten","primary","middle","high"], sortOrder:1 },
  { name:"English",          nameAr:"اللغة الإنجليزية",    slug:"english",       description:"Reading, writing, grammar, communication",   iconEmoji:"📖", color:"#10b981", stages:["kindergarten","primary","middle","high"], sortOrder:2 },
  { name:"Arabic",           nameAr:"اللغة العربية",        slug:"arabic",        description:"Arabic language, letters, grammar",          iconEmoji:"📝", color:"#f59e0b", stages:["kindergarten","primary","middle","high"], sortOrder:3 },
  { name:"Science",          nameAr:"العلوم",               slug:"science",       description:"Biology, chemistry, physics, enquiry",       iconEmoji:"🔬", color:"#8b5cf6", stages:["primary","middle","high"],              sortOrder:4 },
  { name:"History",          nameAr:"التاريخ",              slug:"history",       description:"British, world and ancient history",         iconEmoji:"📜", color:"#a16207", stages:["primary","middle","high"],              sortOrder:5 },
  { name:"Geography",        nameAr:"الجغرافيا",            slug:"geography",     description:"Physical and human geography",               iconEmoji:"🌍", color:"#14b8a6", stages:["primary","middle","high"],              sortOrder:6 },
  { name:"Computing",        nameAr:"الحوسبة",              slug:"computing",     description:"Programming, algorithms, digital literacy",  iconEmoji:"💻", color:"#0ea5e9", stages:["primary","middle","high"],              sortOrder:7 },
  { name:"Art & Design",     nameAr:"الفن والتصميم",        slug:"art-design",    description:"Creativity, drawing, painting, design",      iconEmoji:"🎨", color:"#ec4899", stages:["kindergarten","primary","middle"],       sortOrder:8 },
  { name:"Phonics & Letters",nameAr:"الحروف والأصوات",      slug:"phonics",       description:"Letters, sounds and early reading",          iconEmoji:"🔤", color:"#f43f5e", stages:["kindergarten"],                         sortOrder:9 },
  { name:"Numbers & Counting",nameAr:"الأرقام والعد",       slug:"early-maths",   description:"Counting, shapes, patterns",                 iconEmoji:"🔢", color:"#6366f1", stages:["kindergarten"],                         sortOrder:10 },
  { name:"World Around Us",  nameAr:"العالم من حولنا",      slug:"world-around",  description:"Animals, nature, seasons",                   iconEmoji:"🌿", color:"#84cc16", stages:["kindergarten"],                         sortOrder:11 },
  { name:"Biology",          nameAr:"الأحياء",              slug:"biology",       description:"GCSE and A-Level Biology",                   iconEmoji:"🧬", color:"#16a34a", stages:["high"],                                 sortOrder:12 },
  { name:"Chemistry",        nameAr:"الكيمياء",             slug:"chemistry",     description:"GCSE and A-Level Chemistry",                 iconEmoji:"⚗️", color:"#9333ea", stages:["high"],                                 sortOrder:13 },
  { name:"Physics",          nameAr:"الفيزياء",             slug:"physics",       description:"GCSE and A-Level Physics",                   iconEmoji:"⚛️", color:"#2563eb", stages:["high"],                                 sortOrder:14 },
];

export const defaultAvatars = [
  // ── Kindergarten cartoon avatars (free) ──────────────────────────────────────
  { name:"Sunny",      nameAr:"صني",      type:"cartoon",     gender:"neutral", description:"A cheerful yellow sun character",      emoji:"☀️",  imageUrl:null, voiceTone:"playful",      stages:["kindergarten"], isPremium:false, sortOrder:1 },
  { name:"Biscuit",    nameAr:"بسكويت",   type:"cartoon",     gender:"neutral", description:"A friendly animated dog",              emoji:"🐶",  imageUrl:null, voiceTone:"playful",      stages:["kindergarten"], isPremium:false, sortOrder:2 },
  { name:"Luna",       nameAr:"لونا",     type:"cartoon",     gender:"female",  description:"A magical moon fairy",                 emoji:"🌙",  imageUrl:null, voiceTone:"gentle",       stages:["kindergarten"], isPremium:false, sortOrder:3 },
  { name:"Robo",       nameAr:"روبو",     type:"cartoon",     gender:"neutral", description:"A friendly learning robot",            emoji:"🤖",  imageUrl:null, voiceTone:"excited",      stages:["kindergarten","primary"], isPremium:false, sortOrder:4 },
  { name:"Leo",        nameAr:"ليو",      type:"cartoon",     gender:"male",    description:"A brave lion cub explorer",            emoji:"🦁",  imageUrl:null, voiceTone:"brave",        stages:["kindergarten","primary"], isPremium:false, sortOrder:5 },
  { name:"Stella",     nameAr:"ستيلا",    type:"cartoon",     gender:"female",  description:"A sparkling star character",           emoji:"⭐",  imageUrl:null, voiceTone:"cheerful",     stages:["kindergarten"], isPremium:false, sortOrder:6 },
  // ── AI Human avatars (premium — subscription required) ────────────────────────
  { name:"Ms. Sarah",  nameAr:"الأستاذة سارة",  type:"ai_human", gender:"female", description:"Professional AI teacher — friendly and encouraging", emoji:null, imageUrl:"/avatars/ms-sarah.jpg",  voiceTone:"warm",        stages:["primary","middle","high"], isPremium:true, sortOrder:10 },
  { name:"Mr. James",  nameAr:"الأستاذ جيمس",   type:"ai_human", gender:"male",   description:"Expert AI tutor — calm and methodical",             emoji:null, imageUrl:"/avatars/mr-james.jpg",  voiceTone:"calm",        stages:["primary","middle","high"], isPremium:true, sortOrder:11 },
  { name:"Dr. Aisha",  nameAr:"د. عائشة",        type:"ai_human", gender:"female", description:"PhD-level AI tutor — specialist in sciences",        emoji:null, imageUrl:"/avatars/dr-aisha.jpg",  voiceTone:"intellectual",stages:["middle","high"],         isPremium:true, sortOrder:12 },
  { name:"Prof. Omar", nameAr:"البروف. عمر",     type:"ai_human", gender:"male",   description:"University professor AI — advanced topics",          emoji:null, imageUrl:"/avatars/prof-omar.jpg", voiceTone:"authoritative",stages:["high"],                   isPremium:true, sortOrder:13 },
];

export const defaultAchievements = [
  { name:"First Steps",    nameAr:"الخطوات الأولى",    description:"Complete your first lesson",      descriptionAr:"أكمل أول درس لك",              iconEmoji:"👶", category:"milestone", xpReward:25,  condition:{type:"lessons_completed",value:1} },
  { name:"Quick Learner",  nameAr:"المتعلم السريع",    description:"Complete 5 lessons",              descriptionAr:"أكمل 5 دروس",                  iconEmoji:"⚡", category:"milestone", xpReward:50,  condition:{type:"lessons_completed",value:5} },
  { name:"Scholar",        nameAr:"العالم",             description:"Complete 20 lessons",             descriptionAr:"أكمل 20 درساً",                iconEmoji:"🎓", category:"milestone", xpReward:150, condition:{type:"lessons_completed",value:20} },
  { name:"Perfect Score",  nameAr:"الدرجة الكاملة",    description:"Score 100% on a quiz",            descriptionAr:"احصل على 100%",                iconEmoji:"💯", category:"academic",  xpReward:75,  condition:{type:"quiz_score",value:100} },
  { name:"3-Day Streak",   nameAr:"3 أيام متتالية",    description:"Learn 3 days in a row",           descriptionAr:"تعلم 3 أيام متتالية",           iconEmoji:"🔥", category:"streak",    xpReward:30,  condition:{type:"streak",value:3} },
  { name:"Week Warrior",   nameAr:"محارب الأسبوع",     description:"Learn 7 days in a row",           descriptionAr:"تعلم 7 أيام متتالية",           iconEmoji:"🏆", category:"streak",    xpReward:100, condition:{type:"streak",value:7} },
  { name:"Math Wizard",    nameAr:"ساحر الرياضيات",    description:"Complete 10 maths lessons",       descriptionAr:"أكمل 10 دروس رياضيات",          iconEmoji:"🧮", category:"subject",   xpReward:150, condition:{type:"subject_lessons",subject:"mathematics",value:10} },
  { name:"Word Master",    nameAr:"سيد الكلمات",       description:"Complete 10 English lessons",     descriptionAr:"أكمل 10 دروس إنجليزية",         iconEmoji:"🔤", category:"subject",   xpReward:100, condition:{type:"subject_lessons",subject:"english",value:10} },
  { name:"Explorer",       nameAr:"المستكشف",           description:"Try 4 different subjects",        descriptionAr:"جرّب 4 مواد مختلفة",            iconEmoji:"🧭", category:"exploration",xpReward:50, condition:{type:"subjects_tried",value:4} },
  { name:"Star Student",   nameAr:"الطالب النجم",      description:"Reach Level 5",                   descriptionAr:"اصل إلى المستوى 5",             iconEmoji:"⭐", category:"level",     xpReward:200, condition:{type:"level",value:5} },
  { name:"Month Champion", nameAr:"بطل الشهر",         description:"30-day learning streak",          descriptionAr:"سلسلة تعلم 30 يوماً",           iconEmoji:"👑", category:"streak",    xpReward:500, condition:{type:"streak",value:30} },
];

// ─── British Curriculum Lessons ───────────────────────────────────────────────
export const defaultLessons = [
  // EYFS
  { title:"Letter A – Apple",     titleAr:"حرف A – تفاحة",  description:"Learn the letter A and its sound (UK Phonics)",  content:`# Letter A 🍎\n\n## The Sound\nThe letter **A** makes the short sound: **"a"** (like in **Apple**, **Ant**, **Axe**)\n\n## Words with A\n- 🍎 **Apple** — a-p-p-l-e\n- 🐜 **Ant** — a-n-t\n- ✈️ **Aeroplane** — starts with A!\n\n## Writing the letter\nStart at the top, go round and down.\n\n## Say it!\n**"a, a, Apple!"** 🎉`, stage:"kindergarten" as const, grade:1, difficulty:"beginner" as const, contentType:"text" as const, durationMinutes:10, xpReward:15, isPublished:true, sortOrder:1, subjectSlug:"phonics" },
  { title:"Letter B – Ball",       titleAr:"حرف B – كرة",   description:"Learn the letter B and its sound", content:`# Letter B 🏀\n\n## The Sound\n**B** makes the sound: **"b"** (like in **Ball**, **Bear**, **Book**)\n\n## Words with B\n- 🏀 **Ball** — b-a-l-l\n- 🐻 **Bear** — b-e-a-r\n- 📚 **Book** — b-o-o-k\n\n## Writing B\nStraight line down, then two bumps on the right.\n\n**"b, b, Ball!"** 🎉`, stage:"kindergarten" as const, grade:1, difficulty:"beginner" as const, contentType:"text" as const, durationMinutes:10, xpReward:15, isPublished:true, sortOrder:2, subjectSlug:"phonics" },
  { title:"Counting 1 to 10",      titleAr:"العد من 1 إلى 10", description:"Count objects up to 10 (EYFS number framework)", content:`# Let's Count to 10! 🔢\n\n1️⃣ **One** 🍎\n2️⃣ **Two** 🍎🍎\n3️⃣ **Three** 🍎🍎🍎\n4️⃣ **Four** 🌟🌟🌟🌟\n5️⃣ **Five** ✋\n6️⃣ **Six** 🌟🌟🌟🌟🌟🌟\n7️⃣ **Seven** 🌈🌈🌈🌈🌈🌈🌈\n8️⃣ **Eight** 🐙 (8 arms!)\n9️⃣ **Nine** 🌟🌟🌟🌟🌟🌟🌟🌟🌟\n🔟 **Ten** ✋✋\n\n## Count your fingers!\nHold up both hands and count all 10 fingers! ✋🤚`, stage:"kindergarten" as const, grade:1, difficulty:"beginner" as const, contentType:"text" as const, durationMinutes:15, xpReward:20, isPublished:true, sortOrder:1, subjectSlug:"early-maths" },
  { title:"Shapes Around Us",      titleAr:"الأشكال من حولنا", description:"Recognise and name 2D shapes", content:`# Shapes Are Everywhere! 🔷\n\n**Circle** ⭕ — Round, no corners\n- 🍕 Pizza, 🌍 Earth, ⏰ Clock\n\n**Square** ⬛ — 4 equal sides, 4 corners\n- 🖼️ Picture frame, 📦 Box face\n\n**Rectangle** 📱 — 4 sides (2 long, 2 short)\n- 📱 Phone, 📚 Book, 🚪 Door\n\n**Triangle** 🔺 — 3 sides, 3 corners\n- 🍕 Pizza slice, ⛰️ Mountain\n\n**Star** ⭐ — 5 points\n\n## Can you find these shapes around you? 🏠`, stage:"kindergarten" as const, grade:1, difficulty:"beginner" as const, contentType:"text" as const, durationMinutes:15, xpReward:20, isPublished:true, sortOrder:2, subjectSlug:"early-maths" },
  // Primary
  { title:"Place Value: Tens and Ones", titleAr:"القيمة المكانية", description:"Understand place value for two-digit numbers (Year 1/2)", content:`# Place Value 🏠\n\nEvery digit has a **place** that tells us its value.\n\n## The number 34\n- **3** in the **tens** place = 30\n- **4** in the **ones** place = 4\n- 30 + 4 = **34**\n\n## Examples\n- **25** = 2 tens + 5 ones\n- **47** = 4 tens + 7 ones\n- **60** = 6 tens + 0 ones\n\n## Key vocabulary\n**digit · tens · ones · value · represent**`, stage:"primary" as const, grade:1, difficulty:"beginner" as const, contentType:"text" as const, durationMinutes:20, xpReward:25, isPublished:true, sortOrder:1, subjectSlug:"mathematics" },
  { title:"Addition within 20",    titleAr:"الجمع حتى 20",  description:"Add single-digit numbers using number bonds (Year 1)", content:`# Addition ➕\n\nAddition means **putting groups together** to find the total.\n\n## Number Bonds to 10 — learn by heart!\n0+10 · 1+9 · 2+8 · 3+7 · 4+6 · 5+5\n\n## Strategy: Make 10!\n8 + 6 = ?\n- 8 + 2 = 10\n- 10 + 4 = **14** ✓\n\n## Count On\n7 + 3 → Start at 7, count: 8, 9, **10** ✓\n\n## Key vocabulary\n**add · plus · total · sum · equals**`, stage:"primary" as const, grade:1, difficulty:"beginner" as const, contentType:"text" as const, durationMinutes:20, xpReward:25, isPublished:true, sortOrder:2, subjectSlug:"mathematics" },
  { title:"Multiplication — 2, 5 and 10 Times Tables", titleAr:"جداول الضرب 2 و5 و10", description:"Learn multiplication facts (Year 2 NC)", content:`# Times Tables 🔢\n\nMultiplication is **fast adding of equal groups**.\n\n## ×2 Table\n1×2=2 · 2×2=4 · 3×2=6 · 4×2=8 · 5×2=10\n6×2=12 · 7×2=14 · 8×2=16 · 9×2=18 · 10×2=20\n\n## ×5 Table\n1×5=5 · 2×5=10 · 3×5=15 · 4×5=20 · 5×5=25\n6×5=30 · 7×5=35 · 8×5=40 · 9×5=45 · 10×5=50\n\n## ×10 Table\nAdd a zero! 7×10=70 · 3×10=30 · 9×10=90\n\n## Tip: Multiplying by 5 ends in 0 or 5`, stage:"primary" as const, grade:3, difficulty:"elementary" as const, contentType:"text" as const, durationMinutes:25, xpReward:30, isPublished:true, sortOrder:3, subjectSlug:"mathematics" },
  { title:"Fractions — Halves and Quarters", titleAr:"الكسور النصف والربع", description:"Understand and find halves and quarters (Year 2)", content:`# Fractions 🍕\n\nA fraction is a **part of a whole**.\n\n## Half (½)\n- Split into **2 equal parts**\n- ½ of 8 = **4**\n\n## Quarter (¼)\n- Split into **4 equal parts**\n- ¼ of 12 = **3**\n\n## Three-Quarters (¾)\n- Three out of four equal parts\n- ¾ of 8 = **6**\n\n## Key words\n**Numerator** (top) — parts we have\n**Denominator** (bottom) — equal parts in total\n\n## Example 🍕\nPizza cut into 4 slices. You eat 1 = **¼** of the pizza.`, stage:"primary" as const, grade:2, difficulty:"elementary" as const, contentType:"text" as const, durationMinutes:25, xpReward:30, isPublished:true, sortOrder:4, subjectSlug:"mathematics" },
  { title:"Nouns, Verbs and Adjectives", titleAr:"الأسماء والأفعال والصفات", description:"Identify and use word classes (Year 2/3 NC)", content:`# Word Classes 📝\n\n## Nouns — naming words\nNames of people, places or things.\n- 🧒 **boy**, 🏫 **school**, 🐕 **dog**\n- **Proper nouns** start with capital letters: *London, Emma, Monday*\n\n## Verbs — action or being words\n- 🏃 **run**, 🎵 **sing**, 💭 **think**\n- The dog **runs**. She **is** happy.\n\n## Adjectives — describing words\n- The **big** dog. The **cold** ice cream.\n\n## Spot them!\n*The __happy__ (adj) __children__ (noun) __played__ (verb) in the __sunny__ (adj) __park__ (noun).*`, stage:"primary" as const, grade:3, difficulty:"elementary" as const, contentType:"text" as const, durationMinutes:25, xpReward:30, isPublished:true, sortOrder:1, subjectSlug:"english" },
  { title:"Plants — Structure and Growth", titleAr:"النباتات — البنية والنمو", description:"Parts of a plant and their functions (Year 2 NC)", content:`# Plants 🌱\n\n## Parts of a Flowering Plant\n\n**Roots** 🌿 — Anchor the plant; absorb water & nutrients\n\n**Stem** 🌿 — Supports the plant; carries water to leaves\n\n**Leaves** 🍃 — Make food using **photosynthesis**\n\n**Flower** 🌸 — Attracts insects for pollination; produces seeds\n\n**Seeds** 🌰 — Contain new plant embryo; dispersed by wind/animals\n\n## What do plants need?\n🌞 Light · 💧 Water · 🌡️ Warmth · 🌍 Nutrients\n\n## Key vocabulary\n**photosynthesis · nutrients · pollination · germination · dispersal**`, stage:"primary" as const, grade:2, difficulty:"elementary" as const, contentType:"text" as const, durationMinutes:25, xpReward:30, isPublished:true, sortOrder:1, subjectSlug:"science" },
  // Middle School
  { title:"Algebra — Solving Linear Equations", titleAr:"الجبر — المعادلات الخطية", description:"Solve one and two-step linear equations (Year 7 / KS3)", content:`# Linear Equations ⚖️\n\n## Golden Rule\n**Whatever you do to one side, do to the other!**\n\n## One-step equations\nx + 7 = 12 → subtract 7 → **x = 5** ✓\n3x = 18   → divide by 3 → **x = 6** ✓\n\n## Two-step equations\n2x + 5 = 13\n→ Step 1: −5 from both sides → 2x = 8\n→ Step 2: ÷2 both sides → **x = 4** ✓\n\n## Always check!\nSubstitute back: 2(4)+5 = 8+5 = 13 ✓\n\n## Key vocabulary\n**variable · coefficient · constant · inverse operation · substitute**`, stage:"middle" as const, grade:7, difficulty:"intermediate" as const, contentType:"text" as const, durationMinutes:35, xpReward:40, isPublished:true, sortOrder:1, subjectSlug:"mathematics" },
  { title:"Ratio and Proportion", titleAr:"النسبة والتناسب", description:"Use and simplify ratios, solve proportion problems (Year 7/8)", content:`# Ratio and Proportion 📊\n\n## Ratio\nCompares two quantities: **a : b**\n\n## Simplifying\nDivide by HCF: 8:12 → HCF=4 → **2:3** ✓\n\n## Sharing in a ratio\nShare £40 in ratio 3:5\n- Total parts = 8\n- 1 part = 40÷8 = £5\n- 3 parts = **£15** · 5 parts = **£25** ✓\n\n## Unitary Method\n4 pens cost £2. How much do 7 cost?\n- 1 pen = £2÷4 = £0.50\n- 7 pens = 7×£0.50 = **£3.50** ✓\n\n## Key vocabulary\n**ratio · proportion · simplify · HCF · unitary method**`, stage:"middle" as const, grade:7, difficulty:"intermediate" as const, contentType:"text" as const, durationMinutes:35, xpReward:45, isPublished:true, sortOrder:2, subjectSlug:"mathematics" },
  { title:"The Particle Model of Matter", titleAr:"نموذج الجسيمات للمادة", description:"Particles in solids, liquids and gases (KS3 Science)", content:`# The Particle Model 🔬\n\nEverything is made of tiny **particles**.\n\n## Solids\n- Closely packed, fixed positions\n- Vibrate but cannot move freely\n- Keep their shape 🧊\n\n## Liquids\n- Close together, not fixed\n- Flow and take container's shape 💧\n\n## Gases\n- Far apart, move rapidly\n- Fill any container 💨\n\n## Changes of State\n| Change | Process | Energy |\n|--------|---------|--------|\n| Solid→Liquid | Melting | Absorbed |\n| Liquid→Gas | Evaporation | Absorbed |\n| Gas→Liquid | Condensation | Released |\n| Liquid→Solid | Freezing | Released |\n\n## Key vocabulary\n**particle · melting point · boiling point · condensation**`, stage:"middle" as const, grade:7, difficulty:"intermediate" as const, contentType:"text" as const, durationMinutes:30, xpReward:40, isPublished:true, sortOrder:1, subjectSlug:"science" },
  // High School
  { title:"Quadratic Equations — Factorising & Formula", titleAr:"المعادلات التربيعية", description:"Solve quadratics by factorising and the quadratic formula (GCSE)", content:`# Quadratic Equations 📐\n\n## Standard form: ax² + bx + c = 0\n\n## Method 1 — Factorising\nx² + 5x + 6 = 0\nFind two numbers: ×=+6, +=+5 → **2 and 3**\n(x+2)(x+3)=0 → **x=−2 or x=−3** ✓\n\n## Method 2 — Quadratic Formula\nx = (−b ± √(b²−4ac)) / 2a\n\nSolve 2x²−7x+3=0: a=2, b=−7, c=3\nDiscriminant = 49−24 = 25\nx = (7±5)/4 → **x=3 or x=½** ✓\n\n## Discriminant b²−4ac\n- >0 : Two real solutions\n- =0 : One repeated solution\n- <0 : No real solutions\n\n## Key vocabulary\n**quadratic · coefficient · discriminant · roots · factorising**`, stage:"high" as const, grade:10, difficulty:"advanced" as const, contentType:"text" as const, durationMinutes:45, xpReward:60, isPublished:true, sortOrder:1, subjectSlug:"mathematics" },
  { title:"Trigonometry — SOHCAHTOA", titleAr:"حساب المثلثات SOHCAHTOA", description:"Use trig ratios to find sides and angles in right triangles (GCSE)", content:`# Trigonometry 📐\n\n## Labelling Sides\n- **H**ypotenuse — longest side (opposite right angle)\n- **O**pposite — opposite the angle θ\n- **A**djacent — next to angle θ\n\n## SOHCAHTOA\n- **S**in θ = Opposite ÷ Hypotenuse\n- **C**os θ = Adjacent ÷ Hypotenuse\n- **T**an θ = Opposite ÷ Adjacent\n\n## Finding a missing side\nAngle=30°, H=10cm. Find O.\nsin30° = O/10 → O = 10×0.5 = **5cm** ✓\n\n## Finding a missing angle\nO=4, A=3. Find θ.\ntanθ = 4/3 = 1.333 → θ = tan⁻¹(1.333) = **53.1°** ✓\n\n## Key vocabulary\n**sine · cosine · tangent · inverse · ratio**`, stage:"high" as const, grade:10, difficulty:"advanced" as const, contentType:"text" as const, durationMinutes:45, xpReward:60, isPublished:true, sortOrder:2, subjectSlug:"mathematics" },
  { title:"Analysing Language in Literature", titleAr:"تحليل اللغة في الأدب", description:"Identify and analyse language techniques — GCSE English Literature", content:`# Language Analysis 📚\n\n## Key Techniques\n\n**Simile** — compare using *like* or *as*\n*"The moon was as white as a bone."*\n→ Cold, eerie, lifeless image.\n\n**Metaphor** — state something IS something else\n*"Life is a journey."*\n→ Implies direction, path, and destination.\n\n**Personification** — give human qualities to objects\n*"The wind whispered through the trees."*\n→ Creates a gentle, mysterious atmosphere.\n\n**Alliteration** — repeat consonant sounds\n*"The snake slithered silently."*\n\n**Onomatopoeia** — words that sound like their meaning\n*"The bees buzzed."*\n\n## PEE Structure\n- **P**oint — state your idea\n- **E**vidence — quote the text\n- **E**xplain — analyse the effect\n\n## Model PEE\n*Shakespeare uses metaphor when he writes "All the world's a stage." This implies that people are merely actors in life, creating a melancholy, fatalistic tone.*`, stage:"high" as const, grade:10, difficulty:"advanced" as const, contentType:"text" as const, durationMinutes:40, xpReward:55, isPublished:true, sortOrder:1, subjectSlug:"english" },
  { title:"DNA and Genetic Inheritance", titleAr:"الحمض النووي والوراثة", description:"DNA structure, genes, chromosomes and inheritance (GCSE Biology)", content:`# DNA and Genetics 🧬\n\n## DNA\n- Stands for **Deoxyribonucleic Acid**\n- Found in the **nucleus** of every cell\n- Shaped like a **double helix**\n- Made of nucleotides: sugar + phosphate + base (A,T,G,C)\n\n## Base Pairing\n- **A** pairs with **T**\n- **G** pairs with **C**\n\n## Chromosomes & Genes\n- Humans: **46 chromosomes** (23 pairs)\n- A **gene** codes for a protein (~25,000 genes)\n\n## Inheritance\n**BB** = homozygous dominant\n**Bb** = heterozygous\n**bb** = homozygous recessive\n\n## Punnett Square (Bb × Bb)\n|   | B  | b  |\n|---|----|----|  \n| B | BB | Bb |\n| b | Bb | bb |\n\nBB(25%) · Bb(50%) · bb(25%)\n\n## Key vocabulary\n**DNA · gene · chromosome · allele · dominant · recessive · genotype · phenotype**`, stage:"high" as const, grade:10, difficulty:"advanced" as const, contentType:"text" as const, durationMinutes:50, xpReward:65, isPublished:true, sortOrder:1, subjectSlug:"biology" },
];

export const defaultQuestions = [
  // EYFS
  { text:"Which letter makes the 'a' sound, like in Apple?", type:"multiple_choice" as const, options:["A","E","O","U"], correctAnswer:"A", explanation:"The letter A makes the short 'a' sound — Apple, Ant, Axe!", difficulty:"beginner" as const, grade:1, stage:"kindergarten" as const, xpReward:5, hints:["Think about the word Apple","First letter of the alphabet"], subjectSlug:"phonics" },
  { text:"How many sides does a triangle have?", type:"multiple_choice" as const, options:["2","3","4","5"], correctAnswer:"3", explanation:"A triangle has exactly 3 sides and 3 corners (vertices).", difficulty:"beginner" as const, grade:1, stage:"kindergarten" as const, xpReward:5, hints:["Tri means three","Count the sides on this shape: 🔺"], subjectSlug:"early-maths" },
  { text:"Count: 🍎🍎🍎🍎🍎 — How many apples?", type:"multiple_choice" as const, options:["4","5","6","7"], correctAnswer:"5", explanation:"Count carefully: 1, 2, 3, 4, 5 — there are 5 apples!", difficulty:"beginner" as const, grade:1, stage:"kindergarten" as const, xpReward:5, hints:["Count one by one","Point to each apple"], subjectSlug:"early-maths" },
  // Primary — Maths
  { text:"What is the value of the digit 5 in the number 52?", type:"multiple_choice" as const, options:["5","50","52","2"], correctAnswer:"50", explanation:"The 5 is in the tens place, so its value is 5 × 10 = 50.", difficulty:"beginner" as const, grade:1, stage:"primary" as const, xpReward:8, hints:["Which column is the 5 in?","Tens column means × 10"], subjectSlug:"mathematics" },
  { text:"What is 6 + 8?", type:"multiple_choice" as const, options:["12","13","14","15"], correctAnswer:"14", explanation:"6 + 8 = 14. Make 10 first: 6 + 4 = 10, then add 4 more = 14.", difficulty:"beginner" as const, grade:1, stage:"primary" as const, xpReward:5, hints:["Make 10 first: 6 + 4","Then add the remaining 4"], subjectSlug:"mathematics" },
  { text:"What is 7 × 5?", type:"multiple_choice" as const, options:["30","35","40","45"], correctAnswer:"35", explanation:"7 × 5 = 35. Count in 5s seven times: 5,10,15,20,25,30,35.", difficulty:"elementary" as const, grade:3, stage:"primary" as const, xpReward:8, hints:["Count in 5s seven times","5 × 7 = same as 7 × 5"], subjectSlug:"mathematics" },
  { text:"What is ¼ of 20?", type:"multiple_choice" as const, options:["4","5","8","10"], correctAnswer:"5", explanation:"¼ of 20 means divide 20 by 4: 20 ÷ 4 = 5.", difficulty:"elementary" as const, grade:2, stage:"primary" as const, xpReward:8, hints:["Divide by the denominator (bottom number)","20 ÷ 4 = ?"], subjectSlug:"mathematics" },
  // Primary — English
  { text:"Which word is a NOUN in: 'The cat sat on the mat.'?", type:"multiple_choice" as const, options:["sat","on","cat","the"], correctAnswer:"cat", explanation:"'Cat' is a noun — it names an animal. 'Sat' is a verb.", difficulty:"elementary" as const, grade:3, stage:"primary" as const, xpReward:8, hints:["A noun is a naming word","It names an animal"], subjectSlug:"english" },
  // Primary — Science
  { text:"What process do plants use to make food using sunlight?", type:"multiple_choice" as const, options:["Respiration","Photosynthesis","Pollination","Germination"], correctAnswer:"Photosynthesis", explanation:"Photosynthesis: plants use sunlight + water + CO₂ to make glucose and oxygen.", difficulty:"elementary" as const, grade:2, stage:"primary" as const, xpReward:10, hints:["'Photo' means light","Think: what do plants need to grow?"], subjectSlug:"science" },
  // Middle School
  { text:"Solve for x:  3x − 4 = 11", type:"multiple_choice" as const, options:["3","4","5","7"], correctAnswer:"5", explanation:"Add 4 to both sides → 3x=15. Divide by 3 → x=5. Check: 3(5)−4=11 ✓", difficulty:"intermediate" as const, grade:7, stage:"middle" as const, xpReward:12, hints:["Add 4 to both sides first","Then divide both sides by 3"], subjectSlug:"mathematics" },
  { text:"Simplify the ratio 24 : 36", type:"multiple_choice" as const, options:["6:9","4:6","2:3","12:18"], correctAnswer:"2:3", explanation:"HCF of 24 and 36 is 12. 24÷12=2, 36÷12=3. Ratio = 2:3.", difficulty:"intermediate" as const, grade:7, stage:"middle" as const, xpReward:12, hints:["Find the Highest Common Factor","Divide both numbers by 12"], subjectSlug:"mathematics" },
  { text:"In the particle model, which state has particles far apart and moving quickly?", type:"multiple_choice" as const, options:["Solid","Liquid","Gas","Plasma"], correctAnswer:"Gas", explanation:"In a gas, particles are far apart and move rapidly in all directions.", difficulty:"intermediate" as const, grade:7, stage:"middle" as const, xpReward:10, hints:["Think about steam from boiling water","Which can be compressed easily?"], subjectSlug:"science" },
  // High School
  { text:"Solve x² − 7x + 12 = 0 by factorising", type:"multiple_choice" as const, options:["x=3 or x=4","x=−3 or x=−4","x=3 or x=−4","x=6 or x=2"], correctAnswer:"x=3 or x=4", explanation:"Find two numbers: ×=12, +=−7 → −3 and −4. (x−3)(x−4)=0 → x=3 or x=4.", difficulty:"advanced" as const, grade:10, stage:"high" as const, xpReward:15, hints:["Find two numbers that multiply to 12 and add to −7","Think: −3 × −4 = 12 and −3+(−4) = −7"], subjectSlug:"mathematics" },
  { text:"sin θ = Opposite ÷ Hypotenuse. If Opp=6 and Hyp=10, what is sin θ?", type:"multiple_choice" as const, options:["0.3","0.6","0.8","1.2"], correctAnswer:"0.6", explanation:"sin θ = 6 ÷ 10 = 0.6 (= 3/5).", difficulty:"advanced" as const, grade:10, stage:"high" as const, xpReward:15, hints:["sin = Opposite / Hypotenuse","Divide 6 by 10"], subjectSlug:"mathematics" },
  { text:"What base pairs with Adenine (A) in DNA?", type:"multiple_choice" as const, options:["Guanine (G)","Cytosine (C)","Thymine (T)","Uracil (U)"], correctAnswer:"Thymine (T)", explanation:"In DNA: A pairs with T, and G pairs with C (complementary base pairing).", difficulty:"advanced" as const, grade:10, stage:"high" as const, xpReward:12, hints:["Remember: A-T and G-C","DNA base pairing is complementary"], subjectSlug:"biology" },
  { text:"Which technique is used in: 'The wind screamed through the night'?", type:"multiple_choice" as const, options:["Simile","Alliteration","Personification","Onomatopoeia"], correctAnswer:"Personification", explanation:"Personification gives the wind the human ability to 'scream', creating a frightening atmosphere.", difficulty:"advanced" as const, grade:10, stage:"high" as const, xpReward:12, hints:["Wind cannot really scream","Which technique gives human traits to non-human things?"], subjectSlug:"english" },
];
